### ISSUE TITLE
StartQuiz command showing the salted hash

### ISSUE THREAD

**Issue by miguelvazsilva** [noescape00/DiscordTipBot#13]
Hello noescape00, i'm msssss, from the Stratis Discord, hope you don't mind that i post here some suggestions and hopefully some bugs about the Discord tipbot you developed.

Some users warned me about being possible to see the salted hash when the StartQuiz command is posted, that doesn't seem alright, there should be a better solution, rather than having to manually delete the command, some possible workarounds:
1 - Just accept the StartQuiz command from a direct message of the user to the tipbot (It's possible right? ), and it would be the tipbot to post automatically the quiz in the Tipping section;
2 - The tipbot could remove automatically the message from the user that ordered the StartQuiz (It's possible to do that by making the tipbot a moderator?).

Thanks, best regards

**Comment by noescape00** [comment]
Yes, that's a good idea. 

First option is probably not the correct way since the bot is supposed to support being added and used in different channels and servers.

I'll probably go with 2nd option and make bot delete the StartQuiz message that contains hash.

**Comment by noescape00** [comment]
fixed in https://github.com/noescape00/DiscordTipBot/commit/93dab1e0a9907e905911b44c7d5d2f8f31a3df84
