### ISSUE TITLE
Error message of data type mismatch

### ISSUE THREAD

**Issue by miguelvazsilva** [noescape00/DiscordTipBot#14]
Hello noescape00,

I noticed that there is at least one parameter in one of the commands of the tipbot, for which the error message is "not worked", this is not a pretty error for a non IT guy (sorry for being too picky, but I am usted working with ERP's):

![image](https://user-images.githubusercontent.com/42476902/44283393-31220380-a256-11e8-8b0e-7ca4f3a69146.png)

Thanks, best regards

**Comment by miguelvazsilva** [comment]
Nice, I suspected there were another commands, without the parameter error messages worked, but didn't wanted to test it directly in the discord, spamming the tipping channel, is there any test environment for the tipbot? I would love to break it :-)

**Comment by noescape00** [comment]
Fixed in https://github.com/noescape00/DiscordTipBot/commit/54fa0409089d5436918102afd20ddeae2f0fd2fc

**Comment by noescape00** [comment]
@miguelvazsilva 
there is a server I use for testing: https://discord.gg/98mgwqq

It has 2 bots: production one that is running on the stratis discord and testing one which is offline 95% of the time and I use it for testing out new features and fixes for the old ones.

**Comment by miguelvazsilva** [comment]
Thanks @noescape00, I already joined the discord.

Will try to do some tests In my spare time, I will try to use the testing bot if it is online, if not, I will use the one that is running in the stratis discord.
