### ISSUE TITLE
Withdraw command should be deleted for security reasons

### ISSUE THREAD

**Issue by miguelvazsilva** [noescape00/DiscordTipBot#19]
For security reasons, the message invoking the withdraw command shouldn't stay posted on discord, because everyone can see easily, that per example by searching discord, the user knijia, should have access to a wallet with 324 Strat, and if the user has a big Strat holding, it could be targeted by hackers:

![image](https://user-images.githubusercontent.com/42476902/44298731-2c099680-a2e0-11e8-81f3-3c4e0c4b3d3d.png)

Of course, the user could delete the message, after invoking it, but I think that the tipbot should warranty this somehow, if you decide in the future to use the 2nd suggestion for the issue #13 , it would fit nicely for this purpose.

Thanks, best regards

**Comment by noescape00** [comment]
@miguelvazsilva this was intentional so that all users can verify that bot actually withdraws specified amount to a target address. 

However I've added a security note in the help message: 
```
Keep in mind that withdrawal address will be publicly visible to all users in this channel. 
To avoid exposing your address use withdraw command in private messages with the bot.
```

**Comment by noescape00** [comment]
Addressed in https://github.com/noescape00/DiscordTipBot/commit/b7584506f16a361df86a470a9cee17209f7ab713
