### ISSUE TITLE
Withdrawal to the Deposit address

### ISSUE THREAD

**Issue by miguelvazsilva** [noescape00/DiscordTipBot#28]
It shouldn't be possible to withdrawal to the deposit address:

![image](https://user-images.githubusercontent.com/42476902/44618217-d138e780-a869-11e8-81f7-b2de1038eec0.png)

**Comment by noescape00** [comment]
fixed in https://github.com/noescape00/DiscordTipBot/commit/2340034f833d8774314c0bd8f0b76d6f74ce7e8a
