### ISSUE TITLE
Tipbot help should mention all commands are prefaced by "tipbot" or @tipbot#xxxx

### ISSUE THREAD

**Issue by acetmesis** [noescape00/DiscordTipBot#29]
Had a couple of people come to me for help with the tipbot because they were copying the commands from help without including "tipbot" at the start. Could be mentioned in the help section?

**Comment by noescape00** [comment]
fixed in https://github.com/noescape00/DiscordTipBot/commit/a09552509f7eb465d2f1cd0c6ab4e6b26fdfa0c6
